// import './globals.css'
// import { Inter } from 'next/font/google'
//
// const inter = Inter({ subsets: ['latin'] })
//
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
//
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
// import { RefreshContext } from "@/refreshContext";
import Navbar from "@/components/navbar/navbar";
import "./global.css";
import ThemeRegistry from "./themeRegistry";

export const metadata = {
  title: "BobUI",
  description: "User interface for Bob (c) qoollo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: "mui" }}>
          <Navbar />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
